### ISSUE TITLE
Horde.Cluster.join_hordes crash on the others node

### ISSUE THREAD

**Issue by meox** [derekkraan/horde#105]
Where is the best place to call Horde.Cluster.join_hordes?

I'm getting this:

```text
pulsar@192.168.0.50: [2019-05-05 20:46:08.883] [info]   Starting Horde.SupervisorImpl with name PulsarSolrIndexer.HordeSupervisor
pulsar@192.168.0.50: [2019-05-05 20:49:52.806] [info]   Starting PulsarSolrIndexer v0.6.0
pulsar@192.168.0.50: [2019-05-05 20:49:52.828] [info]   Starting Horde.SupervisorImpl with name PulsarSolrIndexer.HordeSupervisor
pulsar@192.168.0.50: [2019-05-05 20:49:52.836] [info]   Starting Horde.RegistryImpl with name PulsarSolrIndexer.GRegistry
pulsar@192.168.0.50: [2019-05-05 20:49:52.840] [info]   Starting Elixir.Server.Retry
pulsar@192.168.0.50: [2019-05-05 20:49:52.863] [info]   cleaning task running table
pulsar@192.168.0.50: [2019-05-05 20:49:52.864] [info]   Elixir.SQSConsumer started
pulsar@192.168.0.50: [2019-05-05 20:49:52.869] [info]   ConsumerSupervisor: min_demand = 3, max_demand: 10
pulsar@192.168.0.50: [2019-05-05 20:49:55.323] [error]  GenServer PulsarSolrIndexer.HordeSupervisor.MembersCrdt terminating
** (FunctionClauseError) no function clause matching in DeltaCrdt.CausalCrdt.handle_info/2
    (delta_crdt) lib/delta_crdt/causal_crdt.ex:70: DeltaCrdt.CausalCrdt.handle_info({:add_neighbours, [#PID<19377.302.0>]}, %DeltaCrdt.CausalCrdt{crdt_module: DeltaCrdt.AWLWWMap, crdt_state: %DeltaCrdt.AWLWWMap{dots: %{396184569 => 1}, value: %{"BckHx0Z3wtMTLPsCsjmj/A==" => %{{{:alive, %{members_pid: #PID<0.305.0>, name: PulsarSolrIndexer.HordeSupervisor, pid: #PID<0.307.0>, processes_pid: #PID<0.306.0>}}, 1557082192832923218} => #MapSet<[{396184569, 1}]>}}}, max_sync_size: 200, merkle_map: %MerkleMap{map: %{"BckHx0Z3wtMTLPsCsjmj/A==" => {:alive, %{members_pid: #PID<0.305.0>, name: PulsarSolrIndexer.HordeSupervisor, pid: #PID<0.307.0>, processes_pid: #PID<0.306.0>}}}, merkle_tree: %MerkleMap.MerkleTree{object: {<<212, 241, 216, 124>>, {<<99, 0, 49, 45>>, {<<223, 107, 254, 235>>, {<<147, 120, 219, 150>>, {<<102, 149, 191, 171>>, {<<253, 8, 127, 129>>, [], {<<17, 181, 215, 160>>, [], {"A`\\E", {<<20, 210, 168, 102>>, [], {<<24, 112, 40, 47>>, {<<21, 196, 32, 43>>, {<<65, 152, 231, 228>>, {<<167, 1, 238, 191>>, [], {<<234, 243, 169, 248>>, {<<68, 214, 139, 175>>, {<<172, 29, 229, 84>>, {<<80, 131, 188, 213>>, {<<224, 210, 216, 84>>, {<<76, 132, ...>>, [], {...}}, []}, []}, []}, []}, []}}, []}, []}, []}}, []}}}, []}, []}, []}, []}, []}}}, name: PulsarSolrIndexer.HordeSupervisor.MembersCrdt, neighbour_monitors: %{}, neighbours: #MapSet<[]>, node_id: 396184569, on_diffs: #Function<4.83987349/1 in DeltaCrdt.CausalCrdt.init/1>, outstanding_syncs: %{}, sequence_number: 0, storage_module: nil, sync_interval: 5})
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:add_neighbours, [#PID<19377.302.0>]}
State: %DeltaCrdt.CausalCrdt{crdt_module: DeltaCrdt.AWLWWMap, crdt_state: %DeltaCrdt.AWLWWMap{dots: %{396184569 => 1}, value: %{"BckHx0Z3wtMTLPsCsjmj/A==" => %{{{:alive, %{members_pid: #PID<0.305.0>, name: PulsarSolrIndexer.HordeSupervisor, pid: #PID<0.307.0>, processes_pid: #PID<0.306.0>}}, 1557082192832923218} => #MapSet<[{396184569, 1}]>}}}, max_sync_size: 200, merkle_map: %MerkleMap{map: %{"BckHx0Z3wtMTLPsCsjmj/A==" => {:alive, %{members_pid: #PID<0.305.0>, name: PulsarSolrIndexer.HordeSupervisor, pid: #PID<0.307.0>, processes_pid: #PID<0.306.0>}}}, merkle_tree: %MerkleMap.MerkleTree{object: {<<212, 241, 216, 124>>, {<<99, 0, 49, 45>>, {<<223, 107, 254, 235>>, {<<147, 120, 219, 150>>, {<<102, 149, 191, 171>>, {<<253, 8, 127, 129>>, [], {<<17, 181, 215, 160>>, [], {"A`\\E", {<<20, 210, 168, 102>>, [], {<<24, 112, 40, 47>>, {<<21, 196, 32, 43>>, {<<65, 152, 231, 228>>, {<<167, 1, 238, 191>>, [], {<<234, 243, 169, 248>>, {<<68, 214, 139, 175>>, {<<172, 29, 229, 84>>, {<<80, 131, 188, 213>>, {<<224, 210, 216, 84>>, {<<76, 132, ...>>, [], {...}}, []}, []}, []}, []}, []}}, []}, []}, []}}, []}}}, []}, []}, []}, []}, []}}}, name: PulsarSolrIndexer.HordeSupervisor.MembersCrdt, neighbour_monitors: %{}, neighbours: #MapSet<[]>, node_id: 396184569, on_diffs: #Function<4.83987349/1 in DeltaCrdt.CausalCrdt.init/1>, outstanding_syncs: %{}, sequence_number: 0, storage_module: nil, sync_interval: 5}
pulsar@192.168.0.50: [2019-05-05 20:49:55.326] [error]  GenServer PulsarSolrIndexer.HordeSupervisor terminating
** (stop) exited in: GenServer.call(PulsarSolrIndexer.HordeSupervisor.MembersCrdt, {:operation, {:add, ["BckHx0Z3wtMTLPsCsjmj/A==", {:shutting_down, %{members_pid: #PID<0.305.0>, name: PulsarSolrIndexer.HordeSupervisor, pid: #PID<0.307.0>, processes_pid: #PID<0.306.0>}}]}}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:979: GenServer.call/3
    (horde) lib/horde/supervisor_impl.ex:69: Horde.SupervisorImpl.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.311.0>): :horde_shutting_down
State: %Horde.SupervisorImpl.State{distribution_strategy: Horde.UniformDistribution, members: %{"BckHx0Z3wtMTLPsCsjmj/A==" => {:alive, %{members_pid: #PID<0.305.0>, name: PulsarSolrIndexer.HordeSupervisor, pid: #PID<0.307.0>, processes_pid: #PID<0.306.0>}}}, members_pid: #PID<0.305.0>, name: PulsarSolrIndexer.HordeSupervisor, node_id: "BckHx0Z3wtMTLPsCsjmj/A==", pid: #PID<0.307.0>, processes: %{}, processes_pid: #PID<0.306.0>, processes_updated_at: 0, processes_updated_counter: 0, shutting_down: false}
Client #PID<0.311.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:986: GenServer.call/3
    (horde) lib/horde/signal_shutdown.ex:21: anonymous fn/1 in Horde.SignalShutdown.terminate/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (stdlib) gen_server.erl:673: :gen_server.try_terminate/3
    (stdlib) gen_server.erl:858: :gen_server.terminate/10
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
pulsar@192.168.0.50: [2019-05-05 20:49:55.326] [error]  GenServer #PID<0.311.0> terminating
** (stop) exited in: GenServer.call(PulsarSolrIndexer.HordeSupervisor, :horde_shutting_down, 5000)
    ** (EXIT) exited in: GenServer.call(PulsarSolrIndexer.HordeSupervisor.MembersCrdt, {:operation, {:add, ["BckHx0Z3wtMTLPsCsjmj/A==", {:shutting_down, %{members_pid: #PID<0.305.0>, name: PulsarSolrIndexer.HordeSupervisor, pid: #PID<0.307.0>, processes_pid: #PID<0.306.0>}}]}}, :infinity)
        ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (horde) lib/horde/signal_shutdown.ex:21: anonymous fn/1 in Horde.SignalShutdown.terminate/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (stdlib) gen_server.erl:673: :gen_server.try_terminate/3
    (stdlib) gen_server.erl:858: :gen_server.terminate/10
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.304.0>, :shutdown}
```

**Comment by derekkraan** [comment]
Hi @meox,

I have just released v0.5.0 (this morning). Please upgrade (and note that the API has changed: now you should use [`Horde.Cluster.set_members/2`](https://hexdocs.pm/horde/Horde.Cluster.html#set_members/3))
