### ISSUE TITLE
Registry drops all entries when second node joins

### ISSUE THREAD

**Issue by uberbrodt** [derekkraan/horde#116]
I've created a sample app with instructions on how to replicate https://github.com/uberbrodt/test_horde. 

Briefly, I'm starting a Horde.Supervisor and a Horde.Registry, and a couple of processes that:
1. Join any connected nodes via Horde.Cluster.set_members/2
2. execute a callback to start 10 processes under the Horde.Supervisor, registering them with a via-tuple

As stated in the title, the registry entries seem to work when the first node starts, but when the second one starts and joins, all entries are wiped out for both nodes. Interestingly, all supervised processes move from the first node to the second node. I expected that `UniformDistribution` would place half on the first node and half on the second.

I'm testing with elixir 1.8.1 and OTP 21.3.6. Thanks in advance for looking into this.

**Comment by arjan** [comment]
I think your example might be flawed. In your `HordeLinker` genserver, you effectively create a cluster partition because you [call `set_members` with only the new node](https://github.com/uberbrodt/test_horde/blob/master/lib/test_horde/horde_linker.ex#L44)

I think that on nodeup / nodedown you can just call connect_hordes.

Secondly, the distribution thing is by design. Horde does not try to keep the registries balanced, only when starting a new process it will consider the distribution strategy, but it does not rebalance when joining hordes.

**Comment by uberbrodt** [comment]
@arjan Thanks for taking a look at the issue. I indeed should have updated the linker to use the new way of setting membership. However, doing it the way outlined [here](https://medium.com/@derek.kraan2/whats-new-in-horde-0-5-0-f5a282bc8814) ends in the same behaviour as I described above.

**Comment by uberbrodt** [comment]
Using the lastest master (68ecbd974870c89211f1f6be1a7a709a8958b51d) I now am seeing the registry entries maintained when a second node joins the cluster. However, I do see a crash on the first node related to the CRDT:

```
07:57:03.492 [error] GenServer #PID<0.211.0> terminating
** (stop) exited in: GenServer.call(TestHorde.Supervisor, :horde_shutting_down, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:979: GenServer.call/3
    (horde) lib/horde/signal_shutdown.ex:21: anonymous fn/1 in Horde.SignalShutdown.terminate/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (stdlib) gen_server.erl:673: :gen_server.try_terminate/3
    (stdlib) gen_server.erl:858: :gen_server.terminate/10
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.206.0>, :shutdown}
State: [TestHorde.Supervisor.GracefulShutdownManager, TestHorde.Supervisor]
 
07:57:03.517 [error] GenServer TestHorde.Supervisor.Crdt terminating
** (ArgumentError) argument error
    :erlang.send(TestHorde.Supervisor, {:crdt_update, [{:add, {:member_node_info, {TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}}, %Horde.Supervisor.Member{name: {TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}, status: :dead}}]})
    (horde) lib/horde/supervisor_supervisor.ex:12: anonymous fn/2 in Horde.SupervisorSupervisor.init/1
    (delta_crdt) lib/delta_crdt/causal_crdt.ex:239: DeltaCrdt.CausalCrdt.update_state_with_delta/3
    (delta_crdt) lib/delta_crdt/causal_crdt.ex:184: DeltaCrdt.CausalCrdt.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:diff, %DeltaCrdt.AWLWWMap{dots: %{217186113 => 14, 627012700 => 15}, value: %{{:member_node_info, {TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}} => %{{%Horde.Supervisor.Member{name: {TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}, status: :dead}, 1558443423466354423} => #MapSet<[{627012700, 15}]>}}}, [member_node_info: {TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}]}
State: %DeltaCrdt.CausalCrdt{crdt_module: DeltaCrdt.AWLWWMap, crdt_state: %DeltaCrdt.AWLWWMap{dots: %{217186113 => 14, 627012700 => 14}, value: %{{:member, {TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}} => %{{1, 1558443416733323522} => #MapSet<[{217186113, 2}]>}, {:member, {TestHorde.Supervisor, :"test-horde-2@127.0.0.1"}} => %{{1, 1558443423445634461} => #MapSet<[{217186113, 14}]>}, {:member_node_info, {TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}} => %{{%Horde.Supervisor.Member{name: {TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}, status: :alive}, 1558443416733111634} => #MapSet<[{217186113, 1}]>}, {:member_node_info, {TestHorde.Supervisor, :"test-horde-2@127.0.0.1"}} => %{{%Horde.Supervisor.Member{name: {TestHorde.Supervisor, :"test-horde-2@127.0.0.1"}, status: :alive}, 1558443423298743492} => #MapSet<[{627012700, 1}]>}, {:process, {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_0"}}}} => %{{{{TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_0"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_0"}}]]}}}, 1558443416873124619} => #MapSet<[{217186113, 3}]>, {{{TestHorde.Supervisor, :"test-horde-2@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_0"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_0"}}]]}}}, 1558443423413786311} => #MapSet<[{627012700, 3}]>}, {:process, {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_1"}}}} => %{{{{TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_1"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_1"}}]]}}}, 1558443416873716671} => #MapSet<[{217186113, 4}]>, {{{TestHorde.Supervisor, :"test-horde-2@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_1"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_1"}}]]}}}, 1558443423414468884} => #MapSet<[{627012700, 4}]>}, {:process, {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_10"}}}} => %{{{{TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_10"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_10"}}]]}}}, 1558443416879013301} => #MapSet<[{217186113, 13}]>, {{{TestHorde.Supervisor, :"test-horde-2@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_10"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_10"}}]]}}}, 1558443423419341120} => #MapSet<[{627012700, 13}]>}, {:process, {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_2"}}}} => %{{{{TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_2"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_2"}}]]}}}, 1558443416874334248} => #MapSet<[{217186113, 5}]>, {{{TestHorde.Supervisor, :"test-horde-2@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_2"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_2"}}]]}}}, 1558443423415098953} => #MapSet<[{627012700, 5}]>}, {:process, {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_3"}}}} => %{{{{TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_3"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_3"}}]]}}}, 1558443416874927712} => #MapSet<[{217186113, 6}]>, {{{TestHorde.Supervisor, :"test-horde-2@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_3"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_3"}}]]}}}, 1558443423415722637} => #MapSet<[{627012700, 6}]>}, {:process, {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_4"}}}} => %{{{{TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_4"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_4"}}]]}}}, 1558443416875522897} => #MapSet<[{217186113, 7}]>, {{{TestHorde.Supervisor, :"test-horde-2@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_4"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_4"}}]]}}}, 1558443423416333092} => #MapSet<[{627012700, 7}]>}, {:process, {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_5"}}}} => %{{{{TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_5"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_5"}}]]}}}, 1558443416876108050} => #MapSet<[{217186113, 8}]>, {{{TestHorde.Supervisor, :"test-horde-2@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_5"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_5"}}]]}}}, 1558443423416959148} => #MapSet<[{627012700, 8}]>}, {:process, {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_6"}}}} => %{{{{TestHorde.Supervisor, :"test-horde-1@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_6"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_6"}}]]}}}, 1558443416876659451} => #MapSet<[{217186113, 9}]>, {{{TestHorde.Supervisor, :"test-horde-2@127.0.0.1"}, %{id: {TestGenServer, {:via, Horde.Registry, {TestHorde.Registry, "TestGenServer_6"}}}, restart: :permanent, start: {TestHorde.TestGenServer, :start_link, [[name: {: (truncated)07:57:03.492 [error] GenServer #PID<0.211.0> terminating
** (stop) exited in: GenServer.call(TestHorde.Supervisor, :horde_shutting_down, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:979: GenServer.call/3
    (horde) lib/horde/signal_shutdown.ex:21: anonymous fn/1 in Horde.SignalShutdown.terminate/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (stdlib) gen_server.erl:673: :gen_server.try_terminate/3
    (stdlib) gen_server.erl:858: :gen_server.terminate/10
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.206.0>, :shutdown}
State: [TestHorde.Supervisor.GracefulShutdownManager, TestHorde.Supervisor]
```

**Comment by derekkraan** [comment]
What's happening here is:
1. you start 10 processes on node_1.
2. you start the same 10 processes on node_2.
If step 2 happens before Horde has had a chance to sync up, then processes from node 2 will end up overwriting processes from node 1.
3. Each overwritten process from node_1 gets an EXIT signal and quits.
4. When the 4th process exits, the supervisor goes over its max restarts, and dies. This is causing the crash that you see.

I'm not 100% sure what the best course of action is to deal with this problem. Raising the max_restarts of `Horde.Supervisor` is certainly one. Waiting until Horde.Registry has synced with a neighbour before starting new processes is another.

I'll have to think about this a little longer, because this is a scenario that could play out quite easily after a netsplit. We don't want all supervisors dying after healing a netsplit, that would be weird behaviour.

**Comment by uberbrodt** [comment]
I tested a branch which includes #122 and #123 and it seems to work in my test project (which has been updated to use it). I did however see 1 failing test when running the Horde suite.

**Comment by derekkraan** [comment]
Hi @uberbrodt, the recommended approach will be to handle the `{:name_conflict, _, _, _}` message in your process. In most cases this will mean trapping exits in your process and exiting gracefully when this message is received.

This should address this issue, but if not then feel free to re-open and elaborate.
