### ISSUE TITLE
Unhandled error on SIGTERM

### ISSUE THREAD

**Issue by brndnmtthws** [derekkraan/horde#193]
I noticed this in my logs on shutdown:

```
[info] SIGTERM received - shutting down

[error] GenServer Service.Scheduler.Supervisor terminating
** (stop) exited in: GenServer.stop(Service.Scheduler.Supervisor.ProcessesSupervisor, :normal, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.10.1) lib/gen_server.ex:981: GenServer.stop/3
    (horde 0.7.1) lib/horde/dynamic_supervisor_impl.ex:588: Horde.DynamicSupervisorImpl.shut_down_all_processes/1
    (horde 0.7.1) lib/horde/dynamic_supervisor_impl.ex:365: Horde.DynamicSupervisorImpl.handle_info/2
    (stdlib 3.11.2) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.11.2) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

It seems to be harmless, however it does make a mess of the logs.

I think [the function here](https://github.com/derekkraan/horde/blob/master/lib/horde/processes_supervisor.ex#L526) should gracefully handle the `GenServer.stop/3` error with a try/catch in the event the supervisor has already stopped.

Something like this could work:

```elixir
  def stop(supervisor, reason \\ :normal, timeout \\ :infinity) do
    try do
      GenServer.stop(supervisor, reason, timeout)
    catch
      # process doesn't exist, ignore error
      :exit, {:noproc, _err} -> :ok
    end
  end
```

**Comment by brndnmtthws** [comment]
I think this is the same issue as #154.

Additionally, I noticed another problem where `Horde.DynamicSupervisorImpl` crashes on shutdown because it's trying to update a process that no longer exists:

```
02:11:49.295 [info] shutting down job id=newsletter_d4ec58a4-f07f-4c99-a7e3-e2a1466f792c in Citrine.JobExecutor
02:11:49.295 [info] shutting down job id=newsletter_715a5623-5efb-4e6b-b273-6f271cadd5e1 in Citrine.JobExecutor
02:11:49.310 [error] GenServer Service.Scheduler.HordeSupervisor terminating
** (stop) exited in: GenServer.call(Service.Scheduler.HordeSupervisor.ProcessesSupervisor, {:start_child, {145610857854014902700221807029898722495, {Citrine.JobExecutor, :start_link, [Service.Scheduler.HordeRegistry, %Citrine.Job{extended: false, id: :"newsletter_d4ec58a4-f07f-4c99-a7e3-e2a1466f792c", schedule: "0 0 * * *", task: {Service.Cronjob, :run, [:"newsletter_d4ec58a4-f07f-4c99-a7e3-e2a1466f792c", "d4ec58a4-f07f-4c99-a7e3-e2a1466f792c"]}}]}, :permanent, 60000, :worker, [Citrine.JobExecutor]}}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.10.1) lib/gen_server.ex:1013: GenServer.call/3
    (horde 0.7.1) lib/horde/dynamic_supervisor_impl.ex:739: anonymous fn/2 in Horde.DynamicSupervisorImpl.add_children/2
    (elixir 1.10.1) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (horde 0.7.1) lib/horde/dynamic_supervisor_impl.ex:738: Horde.DynamicSupervisorImpl.add_children/2
    (horde 0.7.1) lib/horde/dynamic_supervisor_impl.ex:733: Horde.DynamicSupervisorImpl.add_child/2
    (horde 0.7.1) lib/horde/dynamic_supervisor_impl.ex:460: Horde.DynamicSupervisorImpl.update_process/2
    (horde 0.7.1) lib/horde/dynamic_supervisor_impl.ex:449: Horde.DynamicSupervisorImpl.update_processes/2
    (horde 0.7.1) lib/horde/dynamic_supervisor_impl.ex:378: Horde.DynamicSupervisorImpl.handle_info/2
Last message: {:crdt_update, [{:add, {:process, 145610857854014902700221807029898722495}, {nil, %{id: 145610857854014902700221807029898722495, restart: :permanent, shutdown: 60000, start: {Citrine.JobExecutor, :start_link, [Service.Scheduler.HordeRegistry, %Citrine.Job{extended: false, id: :"newsletter_d4ec58a4-f07f-4c99-a7e3-e2a1466f792c", schedule: "0 0 * * *", task: {Service.Cronjob, :run, [:"newsletter_d4ec58a4-f07f-4c99-a7e3-e2a1466f792c", "d4ec58a4-f07f-4c99-a7e3-e2a1466f792c"]}}]}, type: :worker}}}]}
```

As near as I can tell, this can also be safely caught and ignored. It's probably not good to have `Horde.DynamicSupervisorImpl` restarting during shutdown.

**Comment by brndnmtthws** [comment]
So I've been doing a lot of testing & debugging on this and found quite a few problems related to shutdown. Since I think I've fixed several of them, and it's a little more complicated than I want, I'm going to close my existing PRs and put together another PR once I have everything sorted out. I'll leave this issue open, and close #195 because it's related.

**Comment by bernardo-martinez** [comment]
@brndnmtthws were you able to solve the issue with `Horde.DynamicSupervisorImpl` crashes?

**Comment by brndnmtthws** [comment]
> @brndnmtthws were you able to solve the issue with `Horde.DynamicSupervisorImpl` crashes?

I think I ended up rewriting parts of the code, but then moved on to other things. I also created this instead to solve my problem: https://github.com/brndnmtthws/citrine

Perhaps it's helpful to you, depending on what you're trying to do.
