### ISSUE TITLE
Stopping Child via  Horde.DynamicSupervisor.terminate_child with via_tuple

### ISSUE THREAD

**Issue by cdesch** [derekkraan/horde#244]
I get this error when [`Horde.DynamicSupervisor.terminate_child`](https://hexdocs.pm/horde/Horde.DynamicSupervisor.html#terminate_child/2) using `via_tuple` to stop a child managed by the `DynamicSupervisor`:

```
     ** (FunctionClauseError) no function clause matching in Horde.DynamicSupervisor.terminate_child/2

     The following arguments were given to Horde.DynamicSupervisor.terminate_child/2:
     
         # 1
         ExDef.HordeSupervisor
     
         # 2
         {:via, Horde.Registry, {ExDef.HordeRegistry, "name104"}}
     
     Attempted function clauses (showing 1 out of 1):
     
         def terminate_child(supervisor, child_pid) when is_pid(child_pid)
     
     stacktrace:
       (horde 0.8.6) lib/horde/dynamic_supervisor.ex:249: Horde.DynamicSupervisor.terminate_child/2
       (elixir 1.13.1) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
       (ex_unit 1.13.1) lib/ex_unit/on_exit_handler.ex:143: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit 1.13.1) lib/ex_unit/on_exit_handler.ex:129: ExUnit.OnExitHandler.on_exit_runner_loop/0
```

In my code, I'm using the name of the process used that I registered with Horde via Tuple:

        ExDef.HordeSupervisor.stop_child(name)

In my `HorderSupervisor` module, I have:

      def stop_child(name) do
        Logger.info("#{__MODULE__} stop_child ")
        Horde.DynamicSupervisor.terminate_child(__MODULE__, via_tuple(name))
      end

and finally, `via_tuple`

     def via_tuple(name), do: {:via, Horde.Registry, {ExDef.HordeRegistry, name}}

I understand that `terminate_child` wants a `pid`, but how can I get that `via_tuple`?

**Comment by cdesch** [comment]
I figured out how to do this, but if there is a better way, please feel free to leave feedback.  _(I need to add error handling in the `terminate_account` function)_.

First, given the process name alias in the registry, look up the `pid`, then call the `stop_child` function in the `HordeSupervisor`:
```
  def terminate_account(name) do
    [pid_tuple | pids] = Horde.Registry.lookup(ExDef.HordeRegistry, name)
    {pid, _} = pid_tuple
    ExDef.HordeSupervisor.stop_child(pid)
  end
```

My `stop_child` function in `ExDef.HordeSupervisor`:

```
  def stop_child(pid) do
    Logger.info("#{__MODULE__} stop_child ")
    Horde.DynamicSupervisor.terminate_child(__MODULE__, pid)
  end
```
